language: r
sudo: false
cache: packages

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
r:
 - oldrel
 - release
 - devel

r_packages:
  - covr

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
- ./travis-tool.sh dump_logs

r_check_args: "--as-cran --run-dontrun"
